package com.zeepoint.communication;
// Generated Apr 12, 2015 2:37:02 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Zeepoint generated by hbm2java
 */

public class RespuestaMiServicioOUT extends BaseOUT {


 public String nombreUsuario;

    public RespuestaMiServicioOUT() {
    }

    /**
     * @return the nombreUsuario
     */
    public String getNombreUsuario() {
        return nombreUsuario;
    }

    /**
     * @param nombreUsuario the nombreUsuario to set
     */
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }


}


